"""Main campaign creation workflow powered by LangGraph."""

from __future__ import annotations

import asyncio
import importlib
import logging
from datetime import datetime, timezone
from typing import Any, Awaitable, Callable

from app.db.mongodb import MongoDB
from app.db.repositories.campaign_repo import CampaignRepository
from app.db.repositories.customer_repo import CustomerRepository
from app.db.repositories.segment_repo import SegmentRepository
from app.models.segment import Segment
from app.db.repositories.variant_repo import VariantRepository
from app.external.mock_campaign_client import MockCampaignClient, MockCampaignAPIError
from app.models.campaign import CampaignStatus
from app.models.customer import Customer
from app.models.variant import CampaignVariant, VariantStatus
from app.orchestration.state import CampaignState, StateManager, create_initial_campaign_state

try:
	from langgraph.graph import END, START, StateGraph
except ImportError:  # pragma: no cover - compatibility fallback
	from langgraph.graph import StateGraph

	START = "__start__"
	END = "__end__"

logger = logging.getLogger(__name__)

MAX_RETRIES = 3
MOCK_API_PAGE_SIZE = 100  # customers per page when paginating Mock API

# Optional agent class references. These are lazily imported to avoid hard
# import-time coupling to provider-specific LangChain packages.
CampaignBriefParserAgent: Any | None = None
CustomerSegmentationAgent: Any | None = None
CampaignStrategyAgent: Any | None = None
ContentGenerationAgent: Any | None = None


def _now_iso() -> str:
	return datetime.now(tz=timezone.utc).isoformat()


async def call_mock_api_with_retry(func: Callable, *args: Any, max_retries: int = MAX_RETRIES, **kwargs: Any) -> Any:
	"""Wrapper for Mock API calls with exponential backoff (5s → 10s → 20s).

	Non-retriable errors (400, 404) are re-raised immediately.
	"""
	import requests

	last_exc: Exception | None = None
	for attempt in range(1, max_retries + 1):
		try:
			return func(*args, **kwargs)
		except MockCampaignAPIError as exc:
			if exc.status_code in (400, 404):
				raise  # validation/not-found errors — don't retry
			last_exc = exc
		except requests.exceptions.Timeout as exc:
			last_exc = exc
			logger.warning("Mock API timeout (attempt %d/%d)", attempt, max_retries)
		except requests.exceptions.HTTPError as exc:
			if exc.response is not None and exc.response.status_code in (502, 503):
				last_exc = exc
				logger.warning("Mock API service unavailable (attempt %d/%d)", attempt, max_retries)
			else:
				raise
		except Exception as exc:
			last_exc = exc
			logger.warning("Mock API error (attempt %d/%d): %s", attempt, max_retries, exc)

		if attempt < max_retries:
			wait = 5 * (2 ** (attempt - 1))  # 5s, 10s, 20s
			await asyncio.sleep(wait)

	raise last_exc  # type: ignore[misc]


def _campaign_state_manager() -> StateManager:
	return StateManager(MongoDB.get_db())


def _resolve_agent_class(current: Any | None, module_name: str, class_name: str) -> Any:
	if current is not None:
		return current
	module = importlib.import_module(module_name)
	return getattr(module, class_name)


def _append_error(state: CampaignState, message: str) -> CampaignState:
	next_state = CampaignState(**dict(state))
	errors = list(next_state.get("error_messages", []))
	errors.append(message)
	next_state["error_messages"] = errors
	return next_state


def _safe_goal(raw_goal: Any) -> str:
	"""Normalise goal to one of the four enum values.

	Accepts a plain string, a new-format dict {"objective": "..."}, or None.
	"""
	if isinstance(raw_goal, dict):
		raw_goal = raw_goal.get("objective", "")
	goal = (raw_goal or "").lower().strip()
	mapping = {
		"sales": "conversion",
		"convert": "conversion",
		"sign": "conversion",
		"brand": "awareness",
		"loyalty": "retention",
		"engage": "engagement",
	}
	if goal in {"awareness", "conversion", "retention", "engagement"}:
		return goal
	for token, normalized in mapping.items():
		if token in goal:
			return normalized
	return "awareness"


def _fallback_parse_brief(state: CampaignState) -> CampaignState:
	"""Fallback strategy when brief parsing agent is unavailable/fails."""
	next_state = CampaignState(**dict(state))
	brief = next_state.get("campaign_brief", "")
	next_state["parsed_data"] = {
		"product_details": {
			"product_name": "Campaign Product",
			"product_description": brief[:180] if brief else "Autogenerated campaign",
			"cta_link": "",
		},
		"target_audience": {},
		"campaign_goal": {"objective": "awareness"},
		"campaign_preferences": {
			"email_tone": "Friendly",
			"campaign_name": "",
			"content_hints": "",
		},
	}
	return next_state


def _fallback_segmentation(state: CampaignState) -> CampaignState:
	"""Fallback segmentation based on age/activity buckets."""
	next_state = CampaignState(**dict(state))
	customers = next_state.get("customers", [])
	segments: dict[str, list[str]] = {
		"active_customers": [],
		"inactive_customers": [],
		"seniors": [],
	}
	for customer in customers:
		cid = customer.get("customer_id")
		if not cid:
			continue
		# Customer dicts use PascalCase field names (model_dump() output)
		existing = str(customer.get("Existing_Customer", "N")).upper()
		app = str(customer.get("App_Installed", "N")).upper()
		age = int(customer.get("Age", 0) or 0)
		if existing == "Y" and app == "Y":
			segments["active_customers"].append(cid)
		else:
			segments["inactive_customers"].append(cid)
		if age >= 50:
			segments["seniors"].append(cid)

	filtered_segments = {name: ids for name, ids in segments.items() if ids}

	# When no customers are available (empty DB + Mock API unavailable), create a
	# placeholder segment so downstream nodes (strategy, content_gen) can proceed.
	if not filtered_segments:
		logger.warning(
			"_fallback_segmentation: no customers available — creating placeholder 'general_audience' segment"
		)
		filtered_segments = {
			"general_audience": []
		}

	next_state["segments"] = filtered_segments
	checkpoint_data = dict(next_state.get("checkpoint_data", {}))
	checkpoint_data["segments_detail"] = [
		{
			"segment_name": name,
			"description": f"Fallback segment: {name}" if ids else "General audience — no customer data available",
			"customer_ids": ids,
			"size": len(ids),
			"targeting_priority": 3,
			"recommended_approach": "Use broad, benefits-driven messaging.",
		}
		for name, ids in filtered_segments.items()
	]
	next_state["checkpoint_data"] = checkpoint_data
	return next_state


def _fallback_content(state: CampaignState) -> CampaignState:
	"""Fallback content generation with deterministic templates."""
	next_state = CampaignState(**dict(state))
	strategy = next_state.get("strategy", {})
	selected_segments = strategy.get("selected_segments") or list(next_state.get("segments", {}).keys())

	generated: list[dict[str, Any]] = []
	for index, segment_name in enumerate(selected_segments, start=1):
		generated.append(
			{
				"variant_id": f"fallback_{segment_name}_{index}",
				"segment_name": segment_name,
				"subject_line": "Exclusive update for your segment",
				"email_body": (
					"<html><body><p>Hi [FIRST_NAME],</p><p>We have an update curated for "
					f"{segment_name}. Click to explore.</p><a href=\"#\">Learn more</a></body></html>"
				),
				"send_time": datetime.now(tz=timezone.utc).isoformat(),
				"variant_type": "fallback",
				"status": VariantStatus.DRAFT.value,
				"personalization_tags": ["[FIRST_NAME]"],
			}
		)

	next_state["variants"] = generated
	return next_state


def _fallback_execution(state: CampaignState) -> CampaignState:
	"""Fallback strategy when execution agent repeatedly fails."""
	next_state = CampaignState(**dict(state))
	next_state["execution_status"] = "failed"
	checkpoint_data = dict(next_state.get("checkpoint_data", {}))
	checkpoint_data["manual_execution_queue"] = {
		"campaign_id": next_state["campaign_id"],
		"queued_at": _now_iso(),
		"variant_ids": [variant.get("variant_id") for variant in next_state.get("variants", [])],
	}
	next_state["checkpoint_data"] = checkpoint_data
	if "mock_api_campaign_ids" not in next_state:
		next_state["mock_api_campaign_ids"] = {}
	return next_state


async def _maybe_call_agent_method(agent: Any, preferred_name: str, fallback_name: str, *args: Any) -> Any:
	"""Call an async method on an agent, preferring the phase-spec name first."""
	if hasattr(agent, preferred_name):
		method = getattr(agent, preferred_name)
		if len(args) == 1 and isinstance(args[0], tuple):
			result = method(*args[0])
		else:
			result = method(*args)
		return await result if asyncio.iscoroutine(result) else result
	if hasattr(agent, fallback_name):
		method = getattr(agent, fallback_name)
		payload = args[0] if len(args) == 1 else args
		result = method(payload)
		return await result if asyncio.iscoroutine(result) else result
	raise AttributeError(
		f"Agent {type(agent).__name__} has neither '{preferred_name}' nor '{fallback_name}'"
	)


def _load_optional_agent(module_name: str, class_name: str) -> Any | None:
	try:
		module = importlib.import_module(module_name)
		return getattr(module, class_name)
	except Exception:
		return None


async def _execute_node_with_retries(
	node_name: str,
	state: CampaignState,
	operation: Callable[[CampaignState], Awaitable[CampaignState]],
	fallback: Callable[[CampaignState], CampaignState] | None = None,
) -> CampaignState:
	"""Run a node with checkpointing, retries, state validation, and persistence."""
	manager = _campaign_state_manager()
	last_error: Exception | None = None

	logger.info("node.enter", extra={"node": node_name, "campaign_id": state.get("campaign_id")})
	for attempt in range(1, MAX_RETRIES + 1):
		try:
			await manager.create_checkpoint(state, current_node=node_name)
			next_state = await operation(CampaignState(**dict(state)))
			if not manager.validate_state(next_state):
				raise ValueError(f"State validation failed at node={node_name}")
			await manager.save_state(next_state, next_state["campaign_id"])
			logger.info(
				"node.exit",
				extra={
					"node": node_name,
					"campaign_id": next_state.get("campaign_id"),
					"attempt": attempt,
					"timestamp": _now_iso(),
				},
			)
			return next_state
		except Exception as exc:  # pragma: no cover - covered via tests with monkeypatch
			last_error = exc
			logger.exception(
				"node.error",
				extra={
					"node": node_name,
					"campaign_id": state.get("campaign_id"),
					"attempt": attempt,
					"error": str(exc),
				},
			)
			if attempt < MAX_RETRIES:
				await asyncio.sleep(2 ** (attempt - 1))

	message = f"{node_name} failed after {MAX_RETRIES} retries: {last_error}"
	failed_state = _append_error(state, message)
	if fallback is not None:
		logger.warning("node.fallback", extra={"node": node_name, "campaign_id": state.get("campaign_id")})
		failed_state = fallback(failed_state)
	await manager.save_state(failed_state, failed_state["campaign_id"])
	return failed_state


async def parse_brief_node(state: CampaignState) -> CampaignState:
	"""Parse campaign brief using CampaignBriefParserAgent."""

	async def _op(current_state: CampaignState) -> CampaignState:
		agent_cls = _resolve_agent_class(
			CampaignBriefParserAgent,
			"app.agents.brief_parser",
			"CampaignBriefParserAgent",
		)
		agent = agent_cls()
		parsed_data = await _maybe_call_agent_method(
			agent,
			"parse",
			"execute",
			current_state["campaign_brief"]
			if hasattr(agent, "parse")
			else {"brief_text": current_state["campaign_brief"]},
		)
		next_state = CampaignState(**dict(current_state))
		llm_dict = parsed_data if isinstance(parsed_data, dict) else dict(parsed_data)

		# Merge: pre-supplied (user-confirmed) values win over LLM extraction.
		# Any field the user left empty falls back to what the LLM extracted.
		existing = dict(current_state.get("parsed_data") or {})
		merged: dict[str, Any] = {**llm_dict}
		for key, user_val in existing.items():
			if user_val not in (None, "", []):
				merged[key] = user_val
		next_state["parsed_data"] = merged

		# Persist the rich parsed data back to the campaign document
		campaign_repo = CampaignRepository(MongoDB.get_db())
		await campaign_repo.update(
			current_state["campaign_id"],
			{"parsed_data": merged},
		)
		return next_state

	return await _execute_node_with_retries(
		"parse_brief",
		state,
		_op,
		fallback=_fallback_parse_brief,
	)


async def fetch_customers_node(state: CampaignState) -> CampaignState:
	"""Fetch customer cohort from Mock Campaign API with pagination, fall back to MongoDB cache."""

	async def _op(current_state: CampaignState) -> CampaignState:
		client = MockCampaignClient()
		next_state = CampaignState(**dict(current_state))
		mock_api_errors: list[dict[str, Any]] = list(next_state.get("mock_api_errors", []))

		try:
			# Get total count (handles cold start via built-in retry)
			total_count = await asyncio.get_event_loop().run_in_executor(
				None, client.get_customer_count
			)
			logger.info("Mock API customer count: %d", total_count)

			# Paginate through all customers
			all_customers: list[dict[str, Any]] = []
			offset = 0
			while offset < total_count:
				batch = await call_mock_api_with_retry(
					lambda o=offset: client.get_customers(limit=MOCK_API_PAGE_SIZE, offset=o)
				)
				if not batch:
					break
				all_customers.extend(batch)
				offset += len(batch)
				if len(batch) < MOCK_API_PAGE_SIZE:
					break

			if not all_customers:
				logger.warning(
					"fetch_customers: Mock API returned 0 customers — falling back to MongoDB cache"
				)
				repo = CustomerRepository(MongoDB.get_db())
				cached = await repo.find_all(limit=10_000)
				next_state["customers"] = [c.model_dump() for c in cached]
				next_state["customer_count"] = len(next_state["customers"])
				if not cached:
					logger.warning(
						"fetch_customers: MongoDB cache also empty — run: python scripts/seed_database.py"
					)
			else:
				logger.info("Fetched %d customers from Mock API", len(all_customers))

				# Cache to MongoDB
				repo = CustomerRepository(MongoDB.get_db())
				customers_to_sync = []
				for raw in all_customers:
					try:
						customers_to_sync.append(Customer.from_mock_api(raw))
					except Exception as parse_exc:
						logger.debug("Skipping invalid customer record: %s", parse_exc)
				if customers_to_sync:
					await repo.sync_from_mock_api(customers_to_sync)

				next_state["customers"] = all_customers
				next_state["customer_count"] = len(all_customers)

		except Exception as exc:
			# Fall back to MongoDB cache
			logger.warning("Mock API customer fetch failed (%s), using MongoDB cache", exc)
			mock_api_errors.append({
				"node": "fetch_customers",
				"error": str(exc),
				"timestamp": _now_iso(),
			})
			repo = CustomerRepository(MongoDB.get_db())
			cached = await repo.find_all(limit=10_000)
			next_state["customers"] = [c.model_dump() for c in cached]
			next_state["customer_count"] = len(next_state["customers"])
			if not cached:
				logger.warning(
					"fetch_customers: MongoDB cache also empty — run: python scripts/seed_database.py"
				)

		next_state["mock_api_errors"] = mock_api_errors
		return next_state

	return await _execute_node_with_retries("fetch_customers", state, _op)


_GENERAL_AUDIENCE = "General audience"


def _target_audience_summary(ta: Any) -> str:
	"""Convert a target_audience value (str or new group dict) to a readable string."""
	if isinstance(ta, str):
		return ta or _GENERAL_AUDIENCE
	if isinstance(ta, dict) and ta:
		parts = []
		for name, grp in ta.items():
			if isinstance(grp, dict):
				non_null = {k: v for k, v in grp.items() if v is not None}
				detail = ", ".join(f"{k}={v}" for k, v in non_null.items())
				parts.append(f"{name}: {detail}" if detail else name)
		return "; ".join(parts) if parts else _GENERAL_AUDIENCE
	return _GENERAL_AUDIENCE


async def segmentation_node(state: CampaignState) -> CampaignState:
	"""Segment customers using CustomerSegmentationAgent."""

	async def _op(current_state: CampaignState) -> CampaignState:
		agent_cls = _resolve_agent_class(
			CustomerSegmentationAgent,
			"app.agents.segmentation",
			"CustomerSegmentationAgent",
		)
		agent = agent_cls()
		parsed_data = current_state.get("parsed_data", {})
		result = await _maybe_call_agent_method(
			agent,
			"segment_customers",
			"execute",
			(
				current_state.get("customers", []),
				parsed_data,
			)
			if hasattr(agent, "segment_customers")
			else {
				"customers": current_state.get("customers", []),
				"target_audience": _target_audience_summary(parsed_data.get("target_audience", {})),
				"campaign_goal": _safe_goal(parsed_data.get("campaign_goal")),
			},
		)

		# Log filter outcome from the new 3-phase agent
		if isinstance(result, dict) and "qualified_count" in result:
			logger.info(
				"segmentation: %d of %d customers qualified after criteria filter",
				result.get("qualified_count", 0),
				result.get("total_customers", 0),
			)

		if isinstance(result, dict) and "segments" in result and isinstance(result["segments"], list):
			segment_entries = result["segments"]
			segments_map = {
				entry.get("segment_name", f"segment_{idx}"): entry.get("customer_ids", [])
				for idx, entry in enumerate(segment_entries, start=1)
			}
		elif isinstance(result, dict):
			segments_map = {
				name: ids for name, ids in result.items() if isinstance(ids, list)
			}
			segment_entries = [
				{
					"segment_name": name,
					"description": f"Segment {name}",
					"customer_ids": ids,
					"size": len(ids),
					"targeting_priority": 3,
					"recommended_approach": "Target with tailored messaging.",
				}
				for name, ids in segments_map.items()
			]
		else:
			raise ValueError("Unexpected segmentation output shape")

		next_state = CampaignState(**dict(current_state))
		next_state["segments"] = segments_map
		checkpoint_data = dict(next_state.get("checkpoint_data", {}))
		checkpoint_data["segments_detail"] = segment_entries
		next_state["checkpoint_data"] = checkpoint_data

		# Persist segments to MongoDB so the API can serve them
		segment_repo = SegmentRepository(MongoDB.get_db())
		campaign_id = current_state["campaign_id"]
		await segment_repo.delete_by_campaign(campaign_id)
		for entry in segment_entries:
			seg = Segment(
				campaign_id=campaign_id,
				segment_name=entry.get("segment_name", ""),
				description=entry.get("description", ""),
				customer_ids=entry.get("customer_ids", []),
			)
			await segment_repo.create(seg)

		return next_state

	return await _execute_node_with_retries(
		"segmentation",
		state,
		_op,
		fallback=_fallback_segmentation,
	)


async def strategy_node(state: CampaignState) -> CampaignState:
	"""Generate campaign strategy using CampaignStrategyAgent."""

	async def _op(current_state: CampaignState) -> CampaignState:
		agent_cls = _resolve_agent_class(
			CampaignStrategyAgent,
			"app.agents.strategy",
			"CampaignStrategyAgent",
		)
		agent = agent_cls()
		parsed_data = dict(current_state.get("parsed_data", {}))
		# Resolve goal string for the agent without mutating the stored parsed_data
		agent_parsed_data = {**parsed_data, "campaign_goal": _safe_goal(parsed_data.get("campaign_goal"))}

		checkpoint_data = dict(current_state.get("checkpoint_data", {}))
		segment_entries = checkpoint_data.get("segments_detail", [])
		result = await _maybe_call_agent_method(
			agent,
			"generate_strategy",
			"execute",
			(
				current_state.get("segments", {}),
				agent_parsed_data,
			)
			if hasattr(agent, "generate_strategy")
			else {
				"parsed_brief": agent_parsed_data,
				"segments": segment_entries,
				"current_time": datetime.now(tz=timezone.utc),
			},
		)
		if not isinstance(result, dict):
			raise ValueError("Unexpected strategy output shape")
		next_state = CampaignState(**dict(current_state))
		next_state["strategy"] = result
		return next_state

	return await _execute_node_with_retries("strategy", state, _op)


async def content_generation_node(state: CampaignState) -> CampaignState:
	"""Generate email variants using ContentGenerationAgent and persist them."""

	async def _op(current_state: CampaignState) -> CampaignState:
		agent_cls = _resolve_agent_class(
			ContentGenerationAgent,
			"app.agents.content_gen",
			"ContentGenerationAgent",
		)
		agent = agent_cls()
		strategy = dict(current_state.get("strategy", {}))
		selected_segments: list[str] = strategy.get("selected_segments") or list(
			current_state.get("segments", {}).keys()
		)
		send_schedule = strategy.get("send_schedule", {})

		checkpoint_data = dict(current_state.get("checkpoint_data", {}))
		segment_entries = checkpoint_data.get("segments_detail", [])
		segment_map = {entry.get("segment_name"): entry for entry in segment_entries}

		campaign_prefix = current_state["campaign_id"].split("-")[0]
		variants: list[dict[str, Any]] = []
		for index, segment_name in enumerate(selected_segments, start=1):
			segment_payload = segment_map.get(
				segment_name,
				{
					"segment_name": segment_name,
					"description": f"Segment {segment_name}",
					"customer_ids": current_state.get("segments", {}).get(segment_name, []),
					"size": len(current_state.get("segments", {}).get(segment_name, [])),
					"targeting_priority": 3,
					"recommended_approach": "Use benefit-led messaging.",
				},
			)
			variant_id = f"{campaign_prefix}_v{index}"
			content = await _maybe_call_agent_method(
				agent,
				"generate_content",
				"execute",
				(
					strategy,
					current_state.get("segments", {}),
				)
				if hasattr(agent, "generate_content")
				else {
					"parsed_brief": current_state.get("parsed_data", {}),
					"segment": segment_payload,
					"variant_id": variant_id,
					"strategy": strategy,
				},
			)

			if isinstance(content, list):
				variants.extend(content)
				continue
			if not isinstance(content, dict):
				raise ValueError("Unexpected content generation output")

			scheduled_at = send_schedule.get(segment_name)
			if isinstance(scheduled_at, str):
				try:
					send_time = datetime.fromisoformat(scheduled_at)
				except ValueError:
					send_time = datetime.now(tz=timezone.utc)
			else:
				send_time = datetime.now(tz=timezone.utc)

			variant_doc = CampaignVariant(
				campaign_id=current_state["campaign_id"],
				variant_id=variant_id,
				segment_name=segment_name,
				subject_line=(content.get("subject_lines") or ["Your update is ready"])[0],
				email_body=content.get("email_body", "A" * 60),
				send_time=send_time,
				variant_type="ab_test",
				personalization_tags=content.get("personalization_tags", []),
				status=VariantStatus.DRAFT,
				customer_ids=segment_payload.get("customer_ids", current_state.get("segments", {}).get(segment_name, [])),
			)
			variants.append(variant_doc.model_dump())

		repo = VariantRepository(MongoDB.get_db())
		for variant_data in variants:
			await repo.create(CampaignVariant(**variant_data))

		next_state = CampaignState(**dict(current_state))
		next_state["variants"] = variants
		return next_state

	return await _execute_node_with_retries(
		"content_generation",
		state,
		_op,
		fallback=_fallback_content,
	)


async def approval_node(state: CampaignState) -> CampaignState:
	"""Wait for human approval and update state based on approval status."""

	async def _op(current_state: CampaignState) -> CampaignState:
		campaign_id = current_state["campaign_id"]

		# Honour force-rejection set by wait_approval_node — prevents infinite loop
		if str(current_state.get("approval_status", "")).lower() == "rejected":
			return CampaignState(**dict(current_state))

		approval_status = "pending"

		approval_agent_cls = _load_optional_agent("app.agents.approval", "ApprovalAgent")
		if approval_agent_cls is not None:
			agent = approval_agent_cls()
			status = await _maybe_call_agent_method(
				agent,
				"check_approval_status",
				"execute",
				campaign_id,
			)
			if isinstance(status, dict):
				approval_status = str(status.get("approval_status", "pending")).lower()
			else:
				approval_status = str(status).lower()
		else:
			campaign_repo = CampaignRepository(MongoDB.get_db())
			campaign = await campaign_repo.find_by_id(campaign_id)
			if campaign is not None:
				if campaign.status == CampaignStatus.APPROVED:
					approval_status = "approved"
				elif campaign.status == CampaignStatus.REJECTED:
					approval_status = "rejected"
				else:
					# Transition DRAFT → PENDING_APPROVAL so the human can act via API
					if campaign.status == CampaignStatus.DRAFT:
						await campaign_repo.update_status(campaign_id, CampaignStatus.PENDING_APPROVAL)
					approval_status = "pending"

		if approval_status not in {"approved", "rejected", "pending"}:
			approval_status = "pending"

		next_state = CampaignState(**dict(current_state))
		next_state["approval_status"] = approval_status
		return next_state

	return await _execute_node_with_retries("approval", state, _op)


async def wait_approval_node(state: CampaignState) -> CampaignState:
	"""Wait node for pending approvals with bounded polling attempts."""

	async def _op(current_state: CampaignState) -> CampaignState:
		next_state = CampaignState(**dict(current_state))
		checkpoint_data = dict(next_state.get("checkpoint_data", {}))
		wait_count = int(checkpoint_data.get("approval_wait_count", 0)) + 1
		checkpoint_data["approval_wait_count"] = wait_count
		checkpoint_data["last_approval_check"] = _now_iso()

		# Avoid unbounded loops in automated execution.
		if wait_count >= int(checkpoint_data.get("max_approval_waits", 3)):
			next_state["approval_status"] = "rejected"

		next_state["checkpoint_data"] = checkpoint_data
		return next_state

	return await _execute_node_with_retries("wait_approval", state, _op)


async def execution_node(state: CampaignState) -> CampaignState:
	"""Execute campaign using ExecutionAgent (Mock API) or fallback execution path."""

	async def _op(current_state: CampaignState) -> CampaignState:
		execution_agent_cls = _load_optional_agent("app.agents.execution", "ExecutionAgent")
		next_state = CampaignState(**dict(current_state))
		mock_api_errors: list[dict[str, Any]] = list(next_state.get("mock_api_errors", []))
		existing_ids: dict[str, str] = dict(next_state.get("mock_api_campaign_ids", {}))

		if execution_agent_cls is not None:
			agent = execution_agent_cls()
			result = await _maybe_call_agent_method(
				agent,
				"execute_campaign",
				"execute",
				current_state["campaign_id"],
				current_state.get("variants", []),
			)
			if isinstance(result, dict):
				next_state["execution_status"] = str(
					result.get("execution_status", "completed")
				)
				# Merge mock_api_campaign_ids from agent result into state
				new_ids: dict[str, str] = result.get("mock_api_campaign_ids", {})
				existing_ids.update(new_ids)
				next_state["mock_api_campaign_ids"] = existing_ids
				next_state["metrics"] = result.get("metrics", next_state.get("metrics", {}))

				# Persist mappings to MongoDB
				manager = _campaign_state_manager()
				for variant_id, mock_campaign_id in new_ids.items():
					try:
						await manager.save_mock_api_mapping(
							current_state["campaign_id"], variant_id, mock_campaign_id
						)
					except Exception as db_exc:
						logger.warning("Failed to save Mock API mapping: %s", db_exc)

				# Track any execution errors from agent
				agent_errors = result.get("metrics", {}).get("errors", [])
				for err in agent_errors:
					mock_api_errors.append({
						"node": "execution",
						"error": err,
						"timestamp": _now_iso(),
					})
			else:
				next_state["execution_status"] = "completed"
		else:
			next_state["execution_status"] = "completed"
			next_state["metrics"] = {
				"emails_scheduled": len(current_state.get("variants", [])),
				"executed_at": _now_iso(),
			}

		next_state["mock_api_errors"] = mock_api_errors
		campaign_repo = CampaignRepository(MongoDB.get_db())
		await campaign_repo.update_status(
			current_state["campaign_id"],
			CampaignStatus.COMPLETED
			if next_state["execution_status"] == "completed"
			else CampaignStatus.EXECUTING,
		)
		return next_state

	return await _execute_node_with_retries(
		"execution",
		state,
		_op,
		fallback=_fallback_execution,
	)


def should_execute(state: CampaignState) -> str:
	"""Route workflow from approval node based on approval status."""
	status = str(state.get("approval_status", "pending")).lower()
	if status == "approved":
		return "execute"
	if status == "rejected":
		return "end"
	return "wait"


def create_campaign_graph() -> Any:
	"""Build and compile the campaign creation workflow graph."""
	graph = StateGraph(CampaignState)

	graph.add_node("parse_brief", parse_brief_node)
	graph.add_node("fetch_customers", fetch_customers_node)
	graph.add_node("segmentation", segmentation_node)
	graph.add_node("strategy", strategy_node)
	graph.add_node("content_generation", content_generation_node)
	graph.add_node("approval", approval_node)
	graph.add_node("wait_approval", wait_approval_node)
	graph.add_node("execution", execution_node)

	graph.add_edge(START, "parse_brief")
	graph.add_edge("parse_brief", "fetch_customers")
	graph.add_edge("fetch_customers", "segmentation")
	graph.add_edge("segmentation", "strategy")
	graph.add_edge("strategy", "content_generation")
	graph.add_edge("content_generation", "approval")
	graph.add_conditional_edges(
		"approval",
		should_execute,
		{
			"execute": "execution",
			"wait": "wait_approval",
			"end": END,
		},
	)
	graph.add_edge("wait_approval", "approval")
	graph.add_edge("execution", END)

	return graph.compile()


async def run_campaign_workflow(campaign_id: str, campaign_brief: str) -> dict[str, Any]:
	"""Execute the full campaign workflow and return final state."""
	manager = _campaign_state_manager()
	initial_state = create_initial_campaign_state(campaign_id, campaign_brief)
	await manager.save_state(initial_state, campaign_id)

	graph = create_campaign_graph()
	final_state = await graph.ainvoke(initial_state, config={"recursion_limit": 50})

	if not isinstance(final_state, dict):
		raise ValueError("Campaign workflow returned non-dict state")

	await manager.save_state(CampaignState(**final_state), campaign_id)
	return final_state


async def recover_workflow(campaign_id: str, checkpoint_id: str) -> dict[str, Any]:
	"""Recover workflow from checkpoint and resume from stored node."""
	manager = _campaign_state_manager()
	checkpoint = await manager.checkpoint_collection.find_one(
		{"checkpoint_id": checkpoint_id, "campaign_id": campaign_id}
	)
	if checkpoint is None:
		raise ValueError(
			f"No checkpoint found for campaign_id={campaign_id}, checkpoint_id={checkpoint_id}"
		)

	restored_state = await manager.restore_from_checkpoint(checkpoint_id)
	current_node = checkpoint.get("current_node", "parse_brief")

	ordered_nodes: list[tuple[str, Callable[[CampaignState], Awaitable[CampaignState]]]] = [
		("parse_brief", parse_brief_node),
		("fetch_customers", fetch_customers_node),
		("segmentation", segmentation_node),
		("strategy", strategy_node),
		("content_generation", content_generation_node),
		("approval", approval_node),
		("execution", execution_node),
	]
	node_names = [name for name, _ in ordered_nodes]
	start_index = node_names.index(current_node) if current_node in node_names else 0

	state = restored_state
	for name, node_fn in ordered_nodes[start_index:]:
		state = await node_fn(state)
		if name == "approval":
			route = should_execute(state)
			if route == "end":
				break
			if route == "wait":
				state = await wait_approval_node(state)
				state = await approval_node(state)
				if should_execute(state) != "execute":
					break

	await manager.save_state(state, campaign_id)
	return dict(state)

